apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-manager-role
  namespace: snake-game
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-manager-binding
  namespace: snake-game
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-manager-role
  apiGroup: rbac.authorization.k8s.io
